os:
- linux
- osx

sudo: require
dist: trusty

addons:
   apt:
      packages:
      - cmake

language: c

compiler:
- gcc
- clang

script:
- mkdir build
- cd build
- cmake .. -DLIBUV_BUILD_TESTS=ON && make && ctest --verbose

notifications:
   email: false
