version: 1.0.{build}

image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- Release
platform:
- x64
- Win32

install:
- cmd: git submodule update --init --recursive

before_build:
- ps: New-Item -ItemType directory -Path "$($env:APPVEYOR_BUILD_FOLDER)\build"
- ps: Set-Location "$($env:APPVEYOR_BUILD_FOLDER)\build"
- ps: '& cmake -A $($env:PLATFORM) $($env:APPVEYOR_BUILD_FOLDER) -DLIBUV_BUILD_TESTS=ON'
build:
   parallel: true
   project: $(APPVEYOR_BUILD_FOLDER)\build\libuv.sln
   verbosity: normal

test_script:
- ps: Set-Location "$($env:APPVEYOR_BUILD_FOLDER)\build"
- ps: '& ctest -C $($env:CONFIGURATION) --verbose'
